"""
THERE IS NO URLS FOR COMMENTS HERE.
I USE DRF-NESTED-ROUTERS.

COMMNETS-URLS ASSOCIATED IN THE STORE APP URLS AS WE EXPECT THEY 

TO  BE  NESTED FOR EACH PRODUCT LIKE 

    /product/<product_pk>/comments/<comment_pk>

"""